[plugin]
name = "coquitts"
description = "Coqui-TTS - Text-to-Speech toolkit"
repo_url = "https://github.com/seu-usuario/asdf-coquitts"
homepage = "https://github.com/coqui-ai/TTS"
license = "MIT"
version = "0.1.0"

[plugin.tools]
coquitts = { description = "Main Coqui-TTS binary" }
tts = { description = "User-friendly TTS wrapper" }

[plugin.install]
requires = ["python3", "pip3", "git"]

[plugin.install.pre]
# Verifica se Python está instalado
check_python = "python3 --version"

# Verifica se pip está instalado
check_pip = "pip3 --version"

# Verifica se git está instalado  
check_git = "git --version"

[plugin.install.post]
# Cria diretórios necessários
create_dirs = [
  "~/.local/share/mise/coquitts-models",
  "~/.config/coquitts"
]

[plugin.env]
COQUITTS_MODEL_DIR = "~/.local/share/mise/coquitts-models"
COQUITTS_CONFIG_DIR = "~/.config/coquitts"

[plugin.links]
coquitts = "bin/coquitts"
tts = "bin/tts"
